# SPDX-FileCopyrightText: 2023 Niels Bouma
#
# SPDX-License-Identifier: Apache-2.0

---

- block:
    - when: changedetection_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"

    - when: changedetection_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"
  tags:
    - setup-all
    - setup-changedetection
    - install-all
    - install-changedetection

- block:
    - when: (not changedetection_playwright_driver_enabled | bool) or (not changedetection_enabled | bool)
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall_playwright_driver.yml"
  tags:
    - setup-all
    - setup-changedetection

- block:
    - when: not changedetection_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
  tags:
    - setup-all
    - setup-changedetection
