# SPDX-FileCopyrightText: 2023 Niels Bouma
#
# SPDX-License-Identifier: Apache-2.0

---
- name: Perform Changedetection.io installation tasks
  when: changedetection_enabled | bool
  tags:
    - setup-all
    - setup-changedetection
    - install-all
    - install-changedetection
  block:
    - name: Validate Changedetection.io configuration
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"
    - name: Install Changedetection.io
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"

- name: Perform Changedetection.io playwright-driver uninstallation tasks
  when: (not changedetection_playwright_driver_enabled | bool) or (not changedetection_enabled | bool)
  tags:
    - setup-all
    - setup-changedetection
  block:
    - name: Uninstall Changedetection.io playwright-driver
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall_playwright_driver.yml"

- name: Perform Changedetection.io uninstallation tasks
  when: not changedetection_enabled | bool
  tags:
    - setup-all
    - setup-changedetection
  block:
    - name: Uninstall Changedetection.io
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
